### ISSUE TITLE
unable to extract ImageNet Weights

### ISSUE THREAD

**Issue by gargatik** [wanggrun/triplet#7]
Hi, I want to use pretrained weights for imagenet but i am unable to extract them due to missing backbone module in provided pretrainied weights by you.

/mnt/train-data-4-hdd/gargatik/ood/triplet$ python tools/extract_backbone_weights.py ./ckpt/release_ep940.pth ./ckpt/release_smooth_ep940.pth
Traceback (most recent call last):
File "tools/extract_backbone_weights.py", line 37, in
main()
File "tools/extract_backbone_weights.py", line 32, in main
raise Exception("Cannot find a backbone module in the checkpoint.")
Exception: Cannot find a backbone module in the checkpoint.

**Comment by gargatik** [comment]
And can you provide infomration regarding openselfsup version and installation(i am unable to locate it). It seems that they removed openselsup with mmselfsup but mmselsup use different libaries to call diffrent functions
